# infra/docker-compose.yml
services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack
    command: ["redis-stack-server","--appendonly","yes","--appendfsync","everysec"]
    ports:
      - "6379:6379"      # Redis
    volumes:
      - redis_data:/data
    restart: unless-stopped

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    ports:
      - "8001:5540"      # UI en http://localhost:8001
    restart: unless-stopped
    # opcional: persistir settings de la UI
    # volumes:
    #   - redis_insight:/data

volumes:
  redis_data:
  # redis_insight:
